version: "3.8"

services:
  # 1. PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: document-hub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data
    networks:
      - document_network

  # 2. MongoDB
  mongodb:
    image: mongo:7.0
    container_name: document-hub-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - document_network

  # 3. Redis (Bạn lỡ xóa mất nên mình thêm lại)
  dochub:
    image: redis:7-alpine
    container_name: document-hub-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - document_network

  # 4. App Spring Boot của bạn
  backend:
    image: document-hub-app:1.0
    container_name: document-hub-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://document-hub-postgres:5432/${DB_NAME}
      - SPRING_DATA_MONGODB_URI=mongodb://document-hub-mongodb:27017/document_hub_logs
      - SPRING_REDIS_HOST=document-hub-redis # Đổi lại gọi theo container_name cho chuẩn
      - SPRING_REDIS_PORT=6379
    depends_on:
      - postgres
      - mongodb
      - dochub
    networks:
      - document_network # Quan trọng: Phải cho vào cùng mạng với DB

  # 5. Cô lễ tân Nginx
  nginx:
    image: nginx:alpine
    container_name: document-hub-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - document_network # Nginx cũng phải chung mạng với Backend

# Khai báo Volumes và Networks chung
volumes:
  postgres_data_v2:
  mongodb_data:

networks:
  document_network:
    driver: bridge
