version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: document-hub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - document_network

  mongodb:
    image: mongo:7.0
    container_name: document-hub-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - document_network

volumes:
  postgres_data:
  mongodb_data:

networks:
  document_network:
    driver: bridge
